export const CAPACITY_ESTIMATION: { [key: string]: { [key: string]: string } } = {
    "en": {
        "heading": "Step 2: Capacity Estimation",
        "usersHeading": "Users",
        "trafficHeading": "Traffic",
        "storageHeading": "Storage",
        "memoryHeading": "Memory",
        "networkHeading": "Network",
        "dailyUsers": "Estimate the number of daily users",
        "maxConcurrentUsers": "Maximum concurrent users during peak hours",
        "readOps": "Calculate expected read per second",
        "writeOps": "Calculate expected write per second",
        "peakReadOps": "Calculate expected read per second in peak traffic periods",
        "peakWriteOps": "Calculate expected write per second in peak traffic periods",
        "storageType": "Consider the different types of data (structured, unstructured, multimedia)",
        "totalAmountStorage": "Estimate the total amount of storage required",
        "growthRate": "Growth rate",
        "includeCacheMemory": "Include the usage of cache",
        "cacheMemorySize": "Estimate how much memory you might need to store frequently accessed data",
        "trafficVolume": "Estimate traffic volume",
        "dataTransferSize": "Evaluate data transfer size"
    },
    "ua": {
        "heading": "Крок 2: Оцінка ємності",
        "usersHeading": "Користувачі",
        "trafficHeading": "Трафік",
        "storageHeading": "Сховище",
        "memoryHeading": "Пам'ять",
        "networkHeading": "Мережа",
        "dailyUsers": "Оцінка кількості щоденних користувачів",
        "maxConcurrentUsers": "Максимум одночасних користувачів у години пік",
        "readOps": "Обчислити очікуване читання за секунду",
        "writeOps": "Обчислити очікуваний запис за секунду",
        "peakReadOps": "Обчислити очікуване читання за секунду в періоди пікового трафіку",
        "peakWriteOps": "Обчислити очікуваний запис за секунду в періоди пікового трафіку",
        "storageType": "Розглянемо різні типи даних (структуровані, неструктуровані, мультимедійні)",
        "totalAmountStorage": "Оцініть загальний необхідний обсяг пам'яті",
        "growthRate": "Швидкість зростання",
        "includeCacheMemory": "Включити використання кешу",
        "cacheMemorySize": "Оцініть, скільки пам'яті може знадобитися для зберігання часто використовуваних даних",
        "trafficVolume": "Оцінка обсягу трафіку",
        "dataTransferSize": "Оцінити розмір передачі даних"
    }
}